name: Lume Build
on: [push]

# Conditional environmental if's      
env:
  UPDATE_DENO: false # false = deploy lume , true = update deno

jobs:
  build_deploy_lume:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.UPDATE_DENO }}
      - uses: actions/checkout@v2
        if: env.UPDATE_DENO != 'true'
        with:
          fetch-depth: 1
      - name: Setup Deno
        if: env.UPDATE_DENO != 'true'
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build site
        if: env.UPDATE_DENO != 'true'
        run: |
          deno run -A https://deno.land/x/lume/ci.ts
      - name: Deploy
        if: env.UPDATE_DENO != 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  
  # Update Deno if env.UPDATE_DENO = true
  deno-update:
    name: deno update
    runs-on: ubuntu-latest
    steps:
      # condition - if UPDATE_DENO = true
      - run: echo '${{ env.UPDATE_DENO }}'
      - name: Checkout
        if: env.UPDATE_DENO == 'true'
        uses: actions/checkout@v2
      - name: Setup deno
        if: env.UPDATE_DENO == 'true'
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - run: deno vendor deps.ts --force
        if: env.UPDATE_DENO == 'true'
  
      - name: pull request on lume update
        if: env.UPDATE_DENO == 'true'
        uses: woodcock3/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates
  
            Auto-generated by [create-pull-request][1]
  
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
